#!/usr/bin/env bash

err() {
  local mesg="$1"; shift
  printf " (remote) \033[1;31merror:\033[0;0m ${mesg}\n" "$@" >&2
  exit 1
}

msg() {
  local mesg="$1"; shift
  printf " (remote) \033[1;32m***\033[0;0m ${mesg}\n" "$@"
}

user="$1"

cleanup() {
  if [[ -n "$path" ]]; then
    rm -rf "$path"
  fi
  exit 1
}

# when the client disconnects our parent dies and we recieve this signal
# so start the cleanup process
trap cleanup SIGHUP SIGTERM SIGINT

template="${HOME}/uploads/${user}/XXXXXXXX"
path=$(mktemp -d "${template}")
if (( $? != 0 )); then
  err "failed to create directory"
  exit 1
fi


msg "receiving files..."
bsdtar -C "${path}" -xvf - <&0 &
pid=$!
exec 0>&-
wait "${pid}"
if (( $? != 0 )); then
  err "failed to unpack received data"
  cleanup
  exit 1
fi

msg "Functionality not implemented yet"

# vim: set ts=2 sts=2 sw=2 et:
