#!/usr/bin/env bash

repo_user=repo
repo_list=(testing core extra community linux multilib devel)

repo_host=archbsd.net
repo_identity=~/.ssh/repo-submit

progname=$0

msg() {
  local mesg="$1"; shift
  printf "\033[1;32m***\033[0;0m ${mesg}\n" "$@"
}

die() {
  local mesg="$1"; shift
  printf "\033[1;31merror:\033[0;0m ${mesg}\n" "$@" >&2
  exit 1
}

usage() {
  cat <<EOF
usage: ${progname} [options] packages...
options:
  -h, --help        show this help message
  -r, --repo=REPO   upload to this repo instead of [testing]
EOF
}

setonce() {
  eval wasset=\${${2}=NOTSET}
  if (( "$wasset" != "NOTESET" )); then
    echo "option $1 can only be used once"
    usage
    exit 1
  fi
  eval "$2=$3"
}

# option parsing
opts=$(getopt -n "$progname" -o 'hr:' -l 'help,repo:' -- "$@")
if (( $? != 0 )); then
  usage >&2
  exit 1
fi
eval set -- "$opts"
while (( $# > 0 )); do
  case "$1" in
    -r|--repo) setonce -r opt_repo "$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    --) shift ; break ;;
    *)  echo "unknown option: $1"; usage; exit 1 ;;
  esac
done

if (( $# == 0 )); then
  usage
  exit 1
fi

# default options
opt_repo="${opt_repo:-testing}"

found=0
for i in "${repo_list[@]}"; do
  if [[ "$i" == "${opt_repo}" ]]; then
    found=1; break;
  fi
done
if (( ! $found )); then
  msg "Warning: repository not recognized: %s" "${opt_repo}"
fi

# And action...!
files=()
check_package() {
  local pkg="$(readlink -f ${1})"
  local sig="${pkg}.sig"
  if [ -f "${sig}" ]; then
    if ! gpg --verify "${sig}" &>/dev/null; then
      die "invalid signature: ${sig}"
    fi
  fi

  if [ ! -f "${sig}" ]; then
    gpg --detach-sign "${pkg}" || die "signing failed"
  fi
  files=("${files[@]}" "$pkg" "$sig")
}

for i in "$@"; do
  check_package "$i"
done

if (( "${#files}" == 0 )); then
  die "No files to upload"
fi

# strip away file paths and upload to the server
msg "sending..."
bsdtar "${cdir[@]}" -cf - -s "|^.*/|${opt_repo}/|" "${files[@]}" \
  | ssh -i "${repo_identity}" "${repo_user}@${repo_host}"

# vim: set ts=2 sts=2 sw=2 et:
